### ISSUE TITLE
Python sdk gRPC health check failure

### ISSUE THREAD

**Issue by cosmic-chichu** [numaproj/numaflow-python#11]
**Describe the bug**
Python sdk uses old gRPC socket https://github.com/numaproj/numaflow-python/blob/496543c787eb447d8c28b5ee881669a01e0bdab4/pynumaflow/_constants.py#L5

**Expected behavior**
Health check for UDF should pass if using the right socket

**Errors**
Error: failed on UDF readiness check, failed on readiness check: context canceled

**Environment (please complete the following information):**

- Kubernetes: [e.g. v1.24.4+k3s1]
- Numaflow-python: [e.g. v0.2.2]

**Additional context**

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment]
Fixed by https://github.com/numaproj/numaflow-python/pull/12.
