### ISSUE TITLE
Decorators for simple message forwarding

### ISSUE THREAD

**Issue by ab93** [numaproj/numaflow-python#24]
# Summary

Decorators can really help simplify the udf definition for simple use cases, e.g. simple forwarding to the next vertex.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by vigith** [comment]
We now have keys and tags. I believe we are in a good place now even though we do not have decorators.
