### ISSUE TITLE
Raising error does not increase the num_delivered, and the server keep retrying the same message

### ISSUE THREAD

**Issue by sandangel** [numaproj/numaflow-python#87]
**Describe the bug**

**To Reproduce**

1. Raise error in Map Handler with Server
2. Check the logs that the Map Handler will run again with same message

**Expected behavior**

Raising error in map handler should crash and gracefully shutdown

**Screenshots**

**Environment (please complete the following information):**

- Kubernetes: [e.g. v1.18.6]
- Numaflow: [e.g. v0.5.1]
- Numalogic: [e.g. v0.2.0]
- Numaflow-python: [e.g. v0.1.1]

**Additional context**

https://numaproj.slack.com/archives/C03GQ3AMHE1/p1681697184895659

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.

**Comment by ashwinidulams** [comment]
If the expectation is that the pod will restart for every user exception, then i dont think thats the right thing to do. 
if thats what is needed, users can force the exit of a udf container in the catch block. 

However, if the intent is to retry for an exception, then i think we should bake that behavior in to gRPC error handling semantics (especially for map).

**Comment by sandangel** [comment]
The problem is more on the num_delivered is not increasing. as discussed in the slack thread.

**Comment by sandangel** [comment]
hmm, May I ask is there nay update on this issue?

**Comment by vigith** [comment]
we added #88, @jy4096/@ashwinidulams is this fixed?

**Comment by sandangel** [comment]
> The problem is more on the num_delivered is not increasing. as discussed in the slack thread.

As mentioned above, num_delivered is not increasing after I raise an exception in map handler function.

**Comment by vigith** [comment]
Is the pod getting restarted after you raise the exception?

**Comment by sandangel** [comment]
I don't think so.

**Comment by vigith** [comment]
This will be resolved via https://github.com/numaproj/numaflow/issues/719

**Comment by vigith** [comment]
will be released in 0.10
